<?php

namespace Database\Seeders;

use App\Models\Application;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ApplicationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('applications')->delete();
        DB::table('applications')->truncate();

        $applications = [
            [
                'name' => 'DELL EMC Storage Manager',
                'short_name' => 'EMC-Storage',
                'description' => 'Piattaforma di gestione storage EMC per monitoraggio e amministrazione controller RAID e non-RAID con interfaccia GUI wizard-driven e CLI per utenti avanzati.',
                'url' => 'https://localhost:8443/emc-storage',
                'project' => 'Infrastruttura Storage',
                'category' => 'Storage Management',
                'icon_url' => 'https://example.com/icons/emc.png',
                'url_documentation' => 'https://www.dell.com/support/manuals/en-us/openmanage-server-administrator',
                'sort_order' => 1,
                'is_active' => true,
                'is_strategic' => true,
                'scientific_owner' => 'Infrastructure Team',
                'internal_technical_contact' => 'storage.admin@company.com',
                'external_technical_contact' => 'DELL Support',
                'external_technical_email' => 'support@dell.com',
                'url_cockpit' => 'https://localhost:8443/emc-console',
                'url_sandbox' => 'https://sandbox.emc.local',
                'support_contract_expiry' => now()->addMonths(12),
                'contract_notes' => 'Contratto di supporto enterprise con SLA 24/7',
                'cpu' => '8 Core Xeon',
                'ram' => '32 GB DDR4',
                'hd' => '2 TB SSD RAID 10',
                'runtime_type' => 'vm',
                'ports' => '8443, 443, 22',
                'has_mfa' => true,
                'backup_strategy' => 'Incremental giornaliero + Full settimanale',
                'client_id' => 'emc-storage-client',
                'client_secret' => 'encrypted_secret_placeholder',
            ],
            [
                'name' => 'SonicWall Firewall Management',
                'short_name' => 'SonicWall-FW',
                'description' => 'Sistema di gestione firewall next-generation con protezione avanzata, analytics di flusso e gestione centralizzata per switch e access point SonicWall.',
                'url' => 'https://firewall.company.com',
                'project' => 'Cybersecurity',
                'category' => 'Network Security',
                'icon_url' => 'https://example.com/icons/sonicwall.png',
                'url_documentation' => 'https://www.sonicwall.com/products/firewalls',
                'sort_order' => 2,
                'is_active' => true,
                'is_strategic' => true,
                'scientific_owner' => 'Security Team',
                'internal_technical_contact' => 'security.admin@company.com',
                'external_technical_contact' => 'SonicWall Support',
                'external_technical_email' => 'support@sonicwall.com',
                'url_cockpit' => 'https://gms.company.com',
                'url_sandbox' => 'https://firewall-test.company.com',
                'support_contract_expiry' => now()->addMonths(6),
                'contract_notes' => 'Licenza enterprise con aggiornamenti signature database',
                'cpu' => '4 Core ARM',
                'ram' => '8 GB',
                'hd' => '256 GB SSD',
                'runtime_type' => 'appliance',
                'ports' => '443, 22, 1194',
                'has_mfa' => true,
                'backup_strategy' => 'Configurazione automatica su cloud storage',
                'client_id' => 'sonicwall-gms-client',
                'client_secret' => 'encrypted_secret_placeholder',
            ],
            [
                'name' => 'VMware vSphere Portal',
                'short_name' => 'vSphere',
                'description' => 'Piattaforma di virtualizzazione enterprise con vCenter Server per gestione centralizzata di host ESXi, macchine virtuali e allocazione risorse.',
                'url' => 'https://vcenter.company.com',
                'project' => 'Virtualizzazione',
                'category' => 'Virtualization',
                'icon_url' => 'https://example.com/icons/vmware.png',
                'url_documentation' => 'https://docs.vmware.com/en/VMware-vSphere/index.html',
                'sort_order' => 3,
                'is_active' => true,
                'is_strategic' => true,
                'scientific_owner' => 'Virtualization Team',
                'internal_technical_contact' => 'vsphere.admin@company.com',
                'external_technical_contact' => 'VMware Support',
                'external_technical_email' => 'support@vmware.com',
                'url_cockpit' => 'https://vcenter.company.com/ui',
                'url_sandbox' => 'https://vcenter-test.company.com',
                'support_contract_expiry' => now()->addMonths(18),
                'contract_notes' => 'Licenza Enterprise Plus con supporto 24/7',
                'cpu' => '16 Core Xeon Platinum',
                'ram' => '128 GB DDR4',
                'hd' => '10 TB SSD NVMe',
                'runtime_type' => 'vm',
                'ports' => '443, 902, 903',
                'has_mfa' => true,
                'backup_strategy' => 'VM backup giornaliero con retention 30 giorni',
                'client_id' => 'vsphere-sso-client',
                'client_secret' => 'encrypted_secret_placeholder',
            ],
            [
                'name' => 'WSO2 Identity Server',
                'short_name' => 'WSO2-IS',
                'description' => 'Piattaforma IAM open source con supporto SAML2, OAuth2, OIDC per gestione identità utenti, API e AI agent con estensibilità avanzata.',
                'url' => 'https://wso2.company.com',
                'project' => 'Identity Management',
                'category' => 'Security & IAM',
                'icon_url' => 'https://example.com/icons/wso2.png',
                'url_documentation' => 'https://wso2.com/identity-server/',
                'sort_order' => 4,
                'is_active' => true,
                'is_strategic' => true,
                'scientific_owner' => 'Identity Team',
                'internal_technical_contact' => 'wso2.admin@company.com',
                'external_technical_contact' => 'WSO2 Support',
                'external_technical_email' => 'support@wso2.com',
                'url_cockpit' => 'https://wso2.company.com/carbon',
                'url_sandbox' => 'https://wso2-test.company.com',
                'support_contract_expiry' => now()->addMonths(24),
                'contract_notes' => 'Supporto enterprise con aggiornamenti di sicurezza',
                'cpu' => '8 Core Xeon',
                'ram' => '16 GB DDR4',
                'hd' => '500 GB SSD',
                'runtime_type' => 'container',
                'ports' => '9443, 8243, 8280',
                'has_mfa' => true,
                'backup_strategy' => 'Database backup giornaliero + configuration backup',
                'client_id' => 'wso2-admin-client',
                'client_secret' => 'encrypted_secret_placeholder',
            ],
            [
                'name' => 'Grafana Dashboard',
                'short_name' => 'Grafana',
                'description' => 'Piattaforma open source di observability per monitoring, visualizzazione metriche, alerting e dashboard personalizzabili con integrazione AI.',
                'url' => 'https://grafana.company.com',
                'project' => 'Monitoring & Observability',
                'category' => 'Monitoring',
                'icon_url' => 'https://example.com/icons/grafana.png',
                'url_documentation' => 'https://grafana.com/docs/',
                'sort_order' => 5,
                'is_active' => true,
                'is_strategic' => false,
                'scientific_owner' => 'DevOps Team',
                'internal_technical_contact' => 'grafana.admin@company.com',
                'external_technical_contact' => 'Grafana Labs',
                'external_technical_email' => 'support@grafana.com',
                'url_cockpit' => 'https://grafana.company.com/admin',
                'url_sandbox' => 'https://grafana-test.company.com',
                'support_contract_expiry' => now()->addMonths(12),
                'contract_notes' => 'Licenza Cloud Enterprise con SLA 99.9%',
                'cpu' => '4 Core Xeon',
                'ram' => '8 GB DDR4',
                'hd' => '200 GB SSD',
                'runtime_type' => 'container',
                'ports' => '3000, 443, 80',
                'has_mfa' => true,
                'backup_strategy' => 'Dashboard backup giornaliero + database snapshot',
                'client_id' => 'grafana-oauth-client',
                'client_secret' => 'encrypted_secret_placeholder',
            ],
            [
                'name' => 'Log Management System',
                'short_name' => 'LogManager',
                'description' => 'Sistema centralizzato di log management per raccolta, analisi e reporting di eventi da sistemi Windows, Linux, network e cloud.',
                'url' => 'https://logs.company.com',
                'project' => 'Logging & Analytics',
                'category' => 'Log Management',
                'icon_url' => 'https://example.com/icons/logs.png',
                'url_documentation' => 'https://docs.logmanager.com/',
                'sort_order' => 6,
                'is_active' => true,
                'is_strategic' => false,
                'scientific_owner' => 'IT Operations Team',
                'internal_technical_contact' => 'logs.admin@company.com',
                'external_technical_contact' => 'Log Management Vendor',
                'external_technical_email' => 'support@logmanager.com',
                'url_cockpit' => 'https://logs.company.com/admin',
                'url_sandbox' => 'https://logs-test.company.com',
                'support_contract_expiry' => now()->addMonths(9),
                'contract_notes' => 'Licenza enterprise con retention 365 giorni',
                'cpu' => '8 Core Xeon',
                'ram' => '16 GB DDR4',
                'hd' => '1 TB SSD',
                'runtime_type' => 'vm',
                'ports' => '443, 514, 1514',
                'has_mfa' => true,
                'backup_strategy' => 'Log archiving su S3 con retention policy',
                'client_id' => 'logmanager-api-client',
                'client_secret' => 'encrypted_secret_placeholder',
            ],
            [
                'name' => 'MarketPlace FOSSR',
                'short_name' => 'FOSSR-MP',
                'description' => 'Piattaforma marketplace open source basata su OpenStack e Kubernetes per gestione risorse cloud, deployment e orchestrazione container.',
                'url' => 'https://marketplace.fossr.eu',
                'project' => 'FOSSR Infrastructure',
                'category' => 'Cloud Platform',
                'icon_url' => 'https://example.com/icons/fossr.png',
                'url_documentation' => 'https://docs.fossr.eu/',
                'sort_order' => 7,
                'is_active' => true,
                'is_strategic' => true,
                'scientific_owner' => 'FOSSR Development Team',
                'internal_technical_contact' => 'fossr.admin@company.com',
                'external_technical_contact' => 'FOSSR Support',
                'external_technical_email' => 'support@fossr.eu',
                'url_cockpit' => 'https://admin.marketplace.fossr.eu',
                'url_sandbox' => 'https://sandbox.marketplace.fossr.eu',
                'support_contract_expiry' => now()->addMonths(36),
                'contract_notes' => 'Supporto open source con SLA personalizzato',
                'cpu' => '16 Core AMD EPYC',
                'ram' => '64 GB DDR4',
                'hd' => '5 TB SSD NVMe',
                'runtime_type' => 'container',
                'ports' => '443, 6443, 8080',
                'has_mfa' => true,
                'backup_strategy' => 'Backup incrementale giornaliero su object storage',
                'client_id' => 'fossr-marketplace-client',
                'client_secret' => 'encrypted_secret_placeholder',
            ],
            [
                'name' => 'Dassi AI Browser Agent',
                'short_name' => 'Dassi',
                'description' => 'AI browser agent per automazione task web, form filling, data extraction e workflow automation senza codice né RPA bots.',
                'url' => 'https://dassi.company.com',
                'project' => 'AI Automation',
                'category' => 'AI & Automation',
                'icon_url' => 'https://example.com/icons/dassi.png',
                'url_documentation' => 'https://docs.dassi.ai/',
                'sort_order' => 8,
                'is_active' => true,
                'is_strategic' => false,
                'scientific_owner' => 'Digital Transformation Team',
                'internal_technical_contact' => 'dassi.admin@company.com',
                'external_technical_contact' => 'Dassi Support',
                'external_technical_email' => 'support@dassi.ai',
                'url_cockpit' => 'https://dassi.company.com/admin',
                'url_sandbox' => 'https://dassi-test.company.com',
                'support_contract_expiry' => now()->addMonths(12),
                'contract_notes' => 'Licenza SaaS con aggiornamenti automatici',
                'cpu' => '4 Core Xeon',
                'ram' => '8 GB DDR4',
                'hd' => '256 GB SSD',
                'runtime_type' => 'container',
                'ports' => '443, 80, 3000',
                'has_mfa' => true,
                'backup_strategy' => 'Cloud backup con retention 90 giorni',
                'client_id' => 'dassi-oauth-client',
                'client_secret' => 'encrypted_secret_placeholder',
            ],
            [
                'name' => 'OPP FOSSR',
                'short_name' => 'OPP',
                'description' => 'Online Procurement Platform per gestione design, budget, logistica e installazione con oversight centralizzato e critical path management.',
                'url' => 'https://opp.fossr.eu',
                'project' => 'FOSSR Operations',
                'category' => 'Procurement Management',
                'icon_url' => 'https://example.com/icons/opp.png',
                'url_documentation' => 'https://docs.opp.fossr.eu/',
                'sort_order' => 9,
                'is_active' => true,
                'is_strategic' => false,
                'scientific_owner' => 'Procurement Team',
                'internal_technical_contact' => 'opp.admin@company.com',
                'external_technical_contact' => 'OPP Support',
                'external_technical_email' => 'support@opp.fossr.eu',
                'url_cockpit' => 'https://admin.opp.fossr.eu',
                'url_sandbox' => 'https://test.opp.fossr.eu',
                'support_contract_expiry' => now()->addMonths(18),
                'contract_notes' => 'Licenza FOSSR con supporto tecnico dedicato',
                'cpu' => '8 Core Xeon',
                'ram' => '16 GB DDR4',
                'hd' => '500 GB SSD',
                'runtime_type' => 'vm',
                'ports' => '443, 80, 22',
                'has_mfa' => true,
                'backup_strategy' => 'Database backup giornaliero + file storage backup',
                'client_id' => 'opp-fossr-client',
                'client_secret' => 'encrypted_secret_placeholder',
            ],
            [
                'name' => 'PULPO FOSSR',
                'short_name' => 'PULPO',
                'description' => 'Warehouse Management System cloud-native per gestione operazioni warehouse, picking ottimizzato, fleet management e reportistica avanzata.',
                'url' => 'https://pulpo.fossr.eu',
                'project' => 'FOSSR Logistics',
                'category' => 'Warehouse Management',
                'icon_url' => 'https://example.com/icons/pulpo.png',
                'url_documentation' => 'https://www.pulpowms.com/docs/',
                'sort_order' => 10,
                'is_active' => true,
                'is_strategic' => false,
                'scientific_owner' => 'Logistics Team',
                'internal_technical_contact' => 'pulpo.admin@company.com',
                'external_technical_contact' => 'PULPO Support',
                'external_technical_email' => 'support@pulpo.fossr.eu',
                'url_cockpit' => 'https://admin.pulpo.fossr.eu',
                'url_sandbox' => 'https://test.pulpo.fossr.eu',
                'support_contract_expiry' => now()->addMonths(15),
                'contract_notes' => 'Licenza WMS con supporto 24/7 e training incluso',
                'cpu' => '4 Core Xeon',
                'ram' => '12 GB DDR4',
                'hd' => '300 GB SSD',
                'runtime_type' => 'container',
                'ports' => '443, 80, 8443',
                'has_mfa' => true,
                'backup_strategy' => 'Backup incrementale giornaliero su cloud storage',
                'client_id' => 'pulpo-fossr-client',
                'client_secret' => 'encrypted_secret_placeholder',
            ],
            [
                'name' => 'IOPP FOSSR',
                'short_name' => 'IOPP',
                'description' => 'Italian Online Probability Panel per ricerca sociale con dataset rappresentativi, affidabili e di alta qualità scientifica secondo principi FAIR.',
                'url' => 'https://iopp.fossr.eu',
                'project' => 'FOSSR Research',
                'category' => 'Social Research',
                'icon_url' => 'https://example.com/icons/iopp.png',
                'url_documentation' => 'https://www.fossr.eu/en/italian-online-probability-panel-iopp/',
                'sort_order' => 11,
                'is_active' => true,
                'is_strategic' => true,
                'scientific_owner' => 'CNR-IRPPS',
                'internal_technical_contact' => 'iopp.admin@company.com',
                'external_technical_contact' => 'CNR Research',
                'external_technical_email' => 'iopp@irpps.cnr.it',
                'url_cockpit' => 'https://admin.iopp.fossr.eu',
                'url_sandbox' => 'https://test.iopp.fossr.eu',
                'support_contract_expiry' => now()->addMonths(24),
                'contract_notes' => 'Progetto di ricerca finanziato con supporto tecnico CNR',
                'cpu' => '8 Core Xeon',
                'ram' => '32 GB DDR4',
                'hd' => '2 TB SSD',
                'runtime_type' => 'vm',
                'ports' => '443, 80, 22',
                'has_mfa' => true,
                'backup_strategy' => 'Backup dataset giornaliero con retention 10 anni',
                'client_id' => 'iopp-fossr-client',
                'client_secret' => 'encrypted_secret_placeholder',
            ],
        ];

        foreach ($applications as $app) {
            Application::create($app);
        }

        $this->command->info('Created ' . count($applications) . ' applications successfully!');
    }
}
