<?php

namespace Database\Seeders;

use App\Models\Application;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Event;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class ApplicationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable events to prevent observer from firing during seeding
        Event::fake();

        // Disable foreign key checks temporarily
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        // Clear the applications table
        DB::table('applications')->delete();

        // Re-enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $application0s = [
            [
                'name' => 'DELL EMC Storage Manager',
                'short_name' => 'EMC-Storage',
                'description' => 'Piattaforma di gestione storage EMC per monitoraggio e amministrazione controller RAID e non-RAID con interfaccia GUI wizard-driven e CLI per utenti avanzati.',
                'url' => 'https://localhost:8443/emc-storage',
                'project' => 'Infrastruttura Storage',
                'category' => 'Storage Management',
                'icon_url' => 'https://example.com/icons/emc.png',
                'url_documentation' => 'https://www.dell.com/support/manuals/en-us/openmanage-server-administrator',
                'sort_order' => 1,
                'is_active' => true,
                'is_strategic' => true,
                'scientific_owner' => 'Infrastructure Team',
                'internal_technical_contact' => 'storage.admin@company.com',
                'external_technical_contact' => 'DELL Support',
                'external_technical_email' => 'support@dell.com',
                'url_cockpit' => 'https://localhost:8443/emc-console',
                'url_sandbox' => 'https://sandbox.emc.local',
                'support_contract_expiry' => now()->addMonths(12),
                'contract_notes' => 'Contratto di supporto enterprise con SLA 24/7',
                'cpu' => '8 Core Xeon',
                'ram' => '32 GB DDR4',
                'hd' => '2 TB SSD RAID 10',
                'runtime_type' => 'vm',
                'ports' => '8443, 443, 22',
                'has_mfa' => true,
                'backup_strategy' => 'Incremental giornaliero + Full settimanale',
                'backup_replication' => 'Sincrona su storage secondario',
                'url_job_anonimization_db' => 'https://db-anonymization.ced-na.company.com',
                'management_url' => 'https://emc-management.company.com',
                'service_tag' => 'EMC-123456',
                'external_id' => 'EMC-789012',
                'data_sensitivity' => 'common',
                'criticality_level' => 'important',
                'hosting_type' => 'IASS',
                'client_id' => 'emc-storage-client',
                'client_secret' => 'encrypted_secret_placeholder',
            ],
            [
                'name' => 'PowerScale Management',
                'short_name' => 'NAS',
                'description' => 'Piattaforma di storage scale-out Dell PowerScale per la gestione efficiente di dati non strutturati, con analytics avanzate, protezione dei dati e scalabilità orizzontale.',
                'url' => 'https://powerscale.company.com',
                'project' => 'Infrastruttura Storage',
                'category' => 'Storage Management',
                'icon_url' => 'https://example.com/icons/powerscale.png',
                'url_documentation' => 'https://www.dell.com/support/manuals/en-us/powerscale-isilon',
                'sort_order' => 2,
                'is_active' => true,
                'is_strategic' => true,
                'scientific_owner' => 'Infrastructure Team',
                'internal_technical_contact' => 'storage.admin@company.com',
                'external_technical_contact' => 'DELL Support',
                'external_technical_email' => 'support@dell.com',
                'url_cockpit' => 'https://powerscale.company.com/console',
                'url_sandbox' => 'https://powerscale-test.company.com',
                'support_contract_expiry' => now()->addMonths(12),
                'contract_notes' => 'Contratto di supporto enterprise Dell ProSupport Plus',
                'cpu' => '12 Core Intel',
                'ram' => '64 GB',
                'hd' => '100 TB Raw Storage',
                'runtime_type' => 'appliance',
                'ports' => '443, 22, 8080, 111, 2049',
                'has_mfa' => true,
                'backup_strategy' => 'Snapshot orarie + Replicazione remota',
                'backup_replication' => 'Asincrona su cluster secondario',
                'url_job_anonimization_db' => null,
                'management_url' => 'https://powerscale.company.com/admin',
                'service_tag' => 'PS-987654',
                'external_id' => 'PS-321098',
                'data_sensitivity' => 'sensitive',
                'criticality_level' => 'essential',
                'hosting_type' => 'appliance',
                'client_id' => 'powerscale-api-client',
                'client_secret' => 'encrypted_secret_placeholder',
            ],
                  [
                'name' => 'SonicWall Firewall Management',
                'short_name' => 'SonicWall-FW',
                'description' => 'Sistema di gestione firewall next-generation con protezione avanzata, analytics di flusso e gestione centralizzata per switch e access point SonicWall.',
                'url' => 'https://firewall.company.com',
                'project' => 'Cybersecurity',
                'category' => 'Network Security',
                'icon_url' => 'https://example.com/icons/sonicwall.png',
                'url_documentation' => 'https://www.sonicwall.com/products/firewalls',
                'sort_order => 3,
                'is_active' => true,
                'is_strategic' => true,
                'scientific_owner' => 'Security Team',
                'internal_technical_contact' => 'security.admin@company.com',
                'external_technical_contact' => 'SonicWall Support',
                'external_technical_email' => 'support@sonicwall.com',
                'url_cockpit' => 'https://gms.company.com',
                'url_sandbox' => 'https://firewall-test.company.com',
                'support_contract_expiry' => now()->addMonths(6),
                'contract_notes' => 'Licenza enterprise con aggiornamenti signature database',
                'cpu' => '4 Core ARM',
                'ram' => '8 GB',
                'hd' => '256 GB SSD',
                'runtime_type' => 'appliance',
                'ports' => '443, 22, 1194',
                'has_mfa' => true,
                'backup_strategy' => 'Configurazione automatica su cloud storage',
                'backup_replication' => 'Asincrona su backup appliance',
                'url_job_anonimization_db' => null,
                'management_url' => 'https://gms.company.com',
                'service_tag' => 'SNW-987654',
                'external_id' => 'SNW-456789',
                'data_sensitivity' => 'sensitive',
                'criticality_level' => 'essential',
                'hosting_type' => 'appliance',
                'client_id' => 'sonicwall-gms-client',
                'client_secret' => 'encrypted_secret_placeholder',
            ],

            [
                'name' => 'Dashboard VM e Container',
                'short_name' => 'vSphere',
                'description' => 'Piattaforma di  gestione centralizzata di  macchine virtuali e allocazione risorse.',
                'url' => 'https://fossr-gestione.na.icar.cnr.it/',
                'project' => 'FOSSR',
                'category' => 'Virtualization',
                'icon_url' => 'https://example.com/icons/vmware.png',
                'url_documentation' => 'https://docs.vmware.com/en/VMware-vSphere/index.html',
                'sort_order' => 4,
                'is_active' => true,
                'is_strategic' => true,
                'scientific_owner' => 'Virtualization Team',
                'internal_technical_contact' => 'vsphere.admin@company.com',
                'external_technical_contact' => 'VMware Support',
                'external_technical_email' => 'support@vmware.com',
                'url_cockpit' => 'https://vcenter.company.com/ui',
                'url_sandbox' => 'https://vcenter-test.company.com',
                'support_contract_expiry' => now()->addMonths(18),
                'contract_notes' => 'Licenza Enterprise Plus con supporto 24/7',
                'cpu' => '16 Core Xeon Platinum',
                'ram' => '128 GB DDR4',
                'hd' => '10 TB SSD NVMe',
                'runtime_type' => 'vm',
                'ports' => '443, 902, 903',
                'has_mfa' => true,
                'backup_strategy' => 'VM backup giornaliero con retention 30 giorni',
                'backup_replication' => 'Sincrona su DR site',
                'url_job_anonimization_db' => null,
                'management_url' => 'https://vcenter.company.com/ui',
                'service_tag' => 'VMW-555777',
                'external_id' => 'VMW-888999',
                'data_sensitivity' => 'sensitive',
                'criticality_level' => 'essential',
                'hosting_type' => 'IASS',
                'client_id' => 'vsphere-sso-client',
                'client_secret' => 'encrypted_secret_placeholder',
            ],
            [
                'name' => 'WSO2 Identity Server',
                'short_name' => 'WSO2-IS',
                'description' => 'Piattaforma IAM open source con supporto SAML2, OAuth2, OIDC per gestione identità utenti, API e AI agent con estensibilità avanzata.',
                'url' => 'https://auth-fossr.na.icar.cnr.it/',
                'project' => 'FOSSR',
                'category' => 'Security & IAM',
                'icon_url' => 'https://example.com/icons/wso2.png',
                'url_documentation' => 'https://wso2.com/identity-server/',
                'sort_order' => 5,
                'is_active' => true,
                'is_strategic' => true,
                'scientific_owner' => 'Identity Team',
                'internal_technical_contact' => 'wso2.admin@company.com',
                'external_technical_contact' => 'WSO2 Support',
                'external_technical_email' => 'support@wso2.com',
                'url_cockpit' => 'https://wso2.company.com/carbon',
                'url_sandbox' => 'https://wso2-test.company.com',
                'support_contract_expiry' => now()->addMonths(24),
                'contract_notes' => 'Supporto enterprise con aggiornamenti di sicurezza',
                'cpu' => '8 Core Xeon',
                'ram' => '16 GB DDR4',
                'hd' => '500 GB SSD',
                'runtime_type' => 'container',
                'ports' => '9443, 8243, 8280',
                'has_mfa' => true,
                'backup_strategy' => 'Database backup giornaliero + configuration backup',
                'client_id' => 'Q8SXI4GfN2ubFmgyKe3LrPXmacQa',
                'client_secret' => 'FAX5MOX5GKQT_TFBZLNyxc6TutJeFHWEGnfebPwicpca',
            ],
            [
                'name' => 'Grafana Dashboard',
                'short_name' => 'Grafana',
                'description' => 'Piattaforma open source di observability per monitoring, visualizzazione metriche, alerting e dashboard personalizzabili con integrazione AI.',
                'url' => 'https://grafana-fossr-monitoring.na.icar.cnr.it',
                'project' => 'Monitoring & Observability',
                'category' => 'Monitoring',
                'icon_url' => 'https://example.com/icons/grafana.png',
                'url_documentation' => 'https://grafana.com/docs/',
                'sort_order' => 6,
                'is_active' => true,
                'is_strategic' => false,
                'scientific_owner' => 'DevOps Team',
                'internal_technical_contact' => 'grafana.admin@company.com',
                'external_technical_contact' => 'Grafana Labs',
                'external_technical_email' => 'support@grafana.com',
                'url_cockpit' => 'https://grafana.company.com/admin',
                'url_sandbox' => 'https://grafana-test.company.com',
                'support_contract_expiry' => now()->addMonths(12),
                'contract_notes' => 'Licenza Cloud Enterprise con SLA 99.9%',
                'cpu' => '4 Core Xeon',
                'ram' => '8 GB DDR4',
                'hd' => '200 GB SSD',
                'runtime_type' => 'container',
                'ports' => '3000, 443, 80',
                'has_mfa' => true,
                'backup_strategy' => 'Dashboard backup giornaliero + database snapshot',
                'backup_replication' => 'Asincrona su object storage',
                'url_job_anonimization_db' => null,
                'management_url' => 'https://grafana.company.com/admin',
                'service_tag' => 'GRA-111222',
                'external_id' => 'GRA-333444',
                'data_sensitivity' => 'common',
                'criticality_level' => 'standard',
                'hosting_type' => 'container',
                'client_id' => 'grafana-oauth-client',
                'client_secret' => 'encrypted_secret_placeholder',
            ],
              [
                'name' => 'Kibana Dashboard',
                'short_name' => 'Kibana',
                'description' => 'Piattaforma open source di observability per monitoring, visualizzazione metriche, alerting e dashboard personalizzabili con integrazione AI.',
                'url' => 'http://kibana-open.na.icar.cnr.it',
                'project' => 'Monitoring & Observability',
                'category' => 'Monitoring',
                'icon_url' => 'https://example.com/icons/grafana.png',
                'url_documentation' => 'https://grafana.com/docs/',
                'sort_order' => 6,
                'is_active' => true,
                'is_strategic' => false,
                'scientific_owner' => 'DevOps Team',
                'internal_technical_contact' => 'grafana.admin@company.com',
                'external_technical_contact' => 'Grafana Labs',
                'external_technical_email' => 'support@grafana.com',
                'url_cockpit' => 'https://grafana.company.com/admin',
                'url_sandbox' => 'https://grafana-test.company.com',
                'support_contract_expiry' => now()->addMonths(12),
                'contract_notes' => 'Licenza Cloud Enterprise con SLA 99.9%',
                'cpu' => '4 Core Xeon',
                'ram' => '8 GB DDR4',
                'hd' => '200 GB SSD',
                'runtime_type' => 'container',
                'ports' => '3000, 443, 80',
                'has_mfa' => true,
                'backup_strategy' => 'Dashboard backup giornaliero + database snapshot',
                'backup_replication' => 'Asincrona su object storage',
                'url_job_anonimization_db' => null,
                'management_url' => 'https://grafana.company.com/admin',
                'service_tag' => 'GRA-111222',
                'external_id' => 'GRA-333444',
                'data_sensitivity' => 'common',
                'criticality_level' => 'standard',
                'hosting_type' => 'container',
                'client_id' => 'grafana-oauth-client',
                'client_secret' => 'encrypted_secret_placeholder',
            ],
            [
                'name' => 'Log Management System',
                'short_name' => 'LogManager',
                'description' => 'Sistema centralizzato di log management per raccolta, analisi e reporting di eventi da sistemi Windows, Linux, network e cloud.',
                'url' => ' https://fossr-logs.na.icar.cnr.it',
                'project' => 'Logging & Analytics',
                'category' => 'Log Management',
                'icon_url' => 'https://example.com/icons/logs.png',
                'url_documentation' => 'https://docs.logmanager.com/',
                'sort_order' => 7,
                'is_active' => true,
                'is_strategic' => false,
                'scientific_owner' => 'IT Operations Team',
                'internal_technical_contact' => 'logs.admin@company.com',
                'external_technical_contact' => 'Log Management Vendor',
                'external_technical_email' => 'support@logmanager.com',
                'url_cockpit' => 'https://logs.company.com/admin',
                'url_sandbox' => 'https://logs-test.company.com',
                'support_contract_expiry' => now()->addMonths(9),
                'contract_notes' => 'Licenza enterprise con retention 365 giorni',
                'cpu' => '8 Core Xeon',
                'ram' => '16 GB DDR4',
                'hd' => '1 TB SSD',
                'runtime_type' => 'vm',
                'ports' => '443, 514, 1514',
                'has_mfa' => true,
                'backup_strategy' => 'Log archiving su S3 con retention policy',
                'client_id' => 'logmanager-api-client',
                'client_secret' => 'encrypted_secret_placeholder',
            ],
            [
                'name' => 'MarketPlace FOSSR',
                'short_name' => 'FOSSR-MP',
                'description' => 'Piattaforma marketplace open source basata su OpenStack e Kubernetes per gestione risorse cloud, deployment e orchestrazione container.',
                'url' => 'https://fossr-portale.na.icar.cnr.it/',
                'project' => 'FOSSR Infrastructure',
                'category' => 'Cloud Platform',
                'icon_url' => 'https://example.com/icons/fossr.png',
                'url_documentation' => 'https://docs.fossr.eu/',
                'sort_order' => 8,
                'is_active' => true,
                'is_strategic' => true,
                'scientific_owner' => 'FOSSR Development Team',
                'internal_technical_contact' => 'fossr.admin@company.com',
                'external_technical_contact' => 'FOSSR Support',
                'external_technical_email' => 'support@fossr.eu',
                'url_cockpit' => 'https://admin.marketplace.fossr.eu',
                'url_sandbox' => 'https://sandbox.marketplace.fossr.eu',
                'support_contract_expiry' => now()->addMonths(36),
                'contract_notes' => 'Supporto open source con SLA personalizzato',
                'cpu' => '16 Core AMD EPYC',
                'ram' => '64 GB DDR4',
                'hd' => '5 TB SSD NVMe',
                'runtime_type' => 'container',
                'ports' => '443, 6443, 8080',
                'has_mfa' => true,
                'backup_strategy' => 'Backup incrementale giornaliero su object storage',
                'client_id' => 'fossr-marketplace-client',
                'client_secret' => 'encrypted_secret_placeholder',
            ],
            [
                'name' => 'Dassi AI Browser Agent',
                'short_name' => 'Dassi',
                'description' => 'AI browser agent per automazione task web, form filling, data extraction e workflow automation senza codice né RPA bots.',
                'url' => 'https://dassi.company.com',
                'project' => 'AI Automation',
                'category' => 'AI & Automation',
                'icon_url' => 'https://example.com/icons/dassi.png',
                'url_documentation' => 'https://docs.dassi.ai/',
                'sort_order' => 9,
                'is_active' => true,
                'is_strategic' => false,
                'scientific_owner' => 'Digital Transformation Team',
                'internal_technical_contact' => 'dassi.admin@company.com',
                'external_technical_contact' => 'Dassi Support',
                'external_technical_email' => 'support@dassi.ai',
                'url_cockpit' => 'https://dassi.company.com/admin',
                'url_sandbox' => 'https://dassi-test.company.com',
                'support_contract_expiry' => now()->addMonths(12),
                'contract_notes' => 'Licenza SaaS con aggiornamenti automatici',
                'cpu' => '4 Core Xeon',
                'ram' => '8 GB DDR4',
                'hd' => '256 GB SSD',
                'runtime_type' => 'container',
                'ports' => '443, 80, 3000',
                'has_mfa' => true,
                'backup_strategy' => 'Cloud backup con retention 90 giorni',
                'client_id' => 'dassi-oauth-client',
                'client_secret' => 'encrypted_secret_placeholder',
            ],
            [
                'name' => 'OPP FOSSR',
                'short_name' => 'OPP',
                'description' => 'Online Procurement Platform per gestione design, budget, logistica e installazione con oversight centralizzato e critical path management.',
                'url' => 'https://opp.fossr.eu',
                'project' => 'FOSSR Operations',
                'category' => 'Procurement Management',
                'icon_url' => 'https://example.com/icons/opp.png',
                'url_documentation' => 'https://docs.opp.fossr.eu/',
                'sort_order' => 10,
                'is_active' => true,
                'is_strategic' => false,
                'scientific_owner' => 'Procurement Team',
                'internal_technical_contact' => 'opp.admin@company.com',
                'external_technical_contact' => 'OPP Support',
                'external_technical_email' => 'support@opp.fossr.eu',
                'url_cockpit' => 'https://admin.opp.fossr.eu',
                'url_sandbox' => 'https://test.opp.fossr.eu',
                'support_contract_expiry' => now()->addMonths(18),
                'contract_notes' => 'Licenza FOSSR con supporto tecnico dedicato',
                'cpu' => '8 Core Xeon',
                'ram' => '16 GB DDR4',
                'hd' => '500 GB SSD',
                'runtime_type' => 'vm',
                'ports' => '443, 80, 22',
                'has_mfa' => true,
                'backup_strategy' => 'Database backup giornaliero + file storage backup',
                'client_id' => 'opp-fossr-client',
                'client_secret' => 'encrypted_secret_placeholder',
            ],
            [
                'name' => 'PULPO FOSSR',
                'short_name' => 'PULPO',
                'description' => 'Warehouse Management System cloud-native per gestione operazioni warehouse, picking ottimizzato, fleet management e reportistica avanzata.',
                'url' => 'https://pulpo.fossr.eu',
                'project' => 'FOSSR Logistics',
                'category' => 'Warehouse Management',
                'icon_url' => 'https://example.com/icons/pulpo.png',
                'url_documentation' => 'https://www.pulpowms.com/docs/',
                'sort_order' => 11,
                'is_active' => true,
                'is_strategic' => false,
                'scientific_owner' => 'Logistics Team',
                'internal_technical_contact' => 'pulpo.admin@company.com',
                'external_technical_contact' => 'PULPO Support',
                'external_technical_email' => 'support@pulpo.fossr.eu',
                'url_cockpit' => 'https://admin.pulpo.fossr.eu',
                'url_sandbox' => 'https://test.pulpo.fossr.eu',
                'support_contract_expiry' => now()->addMonths(15),
                'contract_notes' => 'Licenza WMS con supporto 24/7 e training incluso',
                'cpu' => '4 Core Xeon',
                'ram' => '12 GB DDR4',
                'hd' => '300 GB SSD',
                'runtime_type' => 'container',
                'ports' => '443, 80, 8443',
                'has_mfa' => true,
                'backup_strategy' => 'Backup incrementale giornaliero su cloud storage',
                'client_id' => 'pulpo-fossr-client',
                'client_secret' => 'encrypted_secret_placeholder',
            ],
            [
                'name' => 'IOPP FOSSR',
                'short_name' => 'IOPP',
                'description' => 'Italian Online Probability Panel per ricerca sociale con dataset rappresentativi, affidabili e di alta qualità scientifica secondo principi FAIR.',
                'url' => 'https://iopp.fossr.eu',
                'project' => 'FOSSR Research',
                'category' => 'Social Research',
                'icon_url' => 'https://example.com/icons/iopp.png',
                'url_documentation' => 'https://www.fossr.eu/en/italian-online-probability-panel-iopp/',
                'sort_order' => 12,
                'is_active' => true,
                'is_strategic' => true,
                'scientific_owner' => 'CNR-IRPPS',
                'internal_technical_contact' => 'iopp.admin@company.com',
                'external_technical_contact' => 'CNR Research',
                'external_technical_email' => 'iopp@irpps.cnr.it',
                'url_cockpit' => 'https://admin.iopp.fossr.eu',
                'url_sandbox' => 'https://test.iopp.fossr.eu',
                'support_contract_expiry' => now()->addMonths(24),
                'contract_notes' => 'Progetto di ricerca finanziato con supporto tecnico CNR',
                'cpu' => '8 Core Xeon',
                'ram' => '32 GB DDR4',
                'hd' => '2 TB SSD',
                'runtime_type' => 'vm',
                'ports' => '443, 80, 22',
                'has_mfa' => true,
                'backup_strategy' => 'Backup dataset giornaliero con retention 10 anni',
                'client_id' => 'iopp-fossr-client',
                'client_secret' => 'encrypted_secret_placeholder',
            ],
            [
                'name' => 'Pannello Sensori CED NA',
                'short_name' => 'Sensori-CED',
                'description' => 'Sistema di monitoraggio sensori ambientali del Centro Elaborazione Dati Nord America con rilevamento temperatura, umidità, pressione e allarmi in tempo reale.',
                'url' => 'https://sensors.ced-na.company.com',
                'project' => 'CED NA Monitoring',
                'category' => 'Environmental Monitoring',
                'icon_url' => 'https://example.com/icons/sensors.png',
                'url_documentation' => 'https://docs.ced-na.company.com/sensors',
                'sort_order' => 13,
                'is_active' => true,
                'is_strategic' => false,
                'scientific_owner' => 'Facilities Team',
                'internal_technical_contact' => 'sensors.admin@company.com',
                'external_technical_contact' => 'Sensor Vendor Support',
                'external_technical_email' => 'support@sensors-vendor.com',
                'url_cockpit' => 'https://sensors.cockpit.ced-na.company.com',
                'url_sandbox' => 'https://sensors-test.ced-na.company.com',
                'support_contract_expiry' => now()->addMonths(8),
                'contract_notes' => 'Manutenzione sensori e calibrazione annuale',
                'cpu' => '2 Core Intel',
                'ram' => '4 GB DDR4',
                'hd' => '128 GB SSD',
                'runtime_type' => 'vm',
                'ports' => '443, 8080, 1883',
                'has_mfa' => true,
                'backup_strategy' => 'Backup dati sensori su storage centrale',
                'client_id' => 'sensors-ced-client',
                'client_secret' => 'encrypted_secret_placeholder',
            ],
            [
                'name' => 'Pannello Condizionamento CED NA',
                'short_name' => 'HVAC-CED',
                'description' => 'Sistema di gestione e controllo impianto di condizionamento del CED Nord America con monitoraggio temperature, umidità e consumo energetico.',
                'url' => 'https://hvac.ced-na.company.com',
                'project' => 'CED NA Infrastructure',
                'category' => 'HVAC Management',
                'icon_url' => 'https://example.com/icons/hvac.png',
                'url_documentation' => 'https://docs.ced-na.company.com/hvac',
                'sort_order' => 14,
                'is_active' => true,
                'is_strategic' => false,
                'scientific_owner' => 'Facilities Team',
                'internal_technical_contact' => 'hvac.admin@company.com',
                'external_technical_contact' => 'HVAC Vendor Support',
                'external_technical_email' => 'support@hvac-vendor.com',
                'url_cockpit' => 'https://hvac.cockpit.ced-na.company.com',
                'url_sandbox' => 'https://hvac-test.ced-na.company.com',
                'support_contract_expiry' => now()->addMonths(10),
                'contract_notes' => 'Manutenzione ordinaria e filtro aria trimestrale',
                'cpu' => '2 Core Intel',
                'ram' => '4 GB DDR4',
                'hd' => '128 GB SSD',
                'runtime_type' => 'vm',
                'ports' => '443, 502, 1911',
                'has_mfa' => true,
                'backup_strategy' => 'Backup configurazione e log eventi',
                'client_id' => 'hvac-ced-client',
                'client_secret' => 'encrypted_secret_placeholder',
            ],
            [
                'name' => 'Pannello Energia CED NA',
                'short_name' => 'Power-CED',
                'description' => 'Sistema di monitoraggio consumi energetici del Centro Elaborazione Dati Nord America con analisi carichi, UPS e PDU in tempo reale.',
                'url' => 'https://power.ced-na.company.com',
                'project' => 'CED NA Power Management',
                'category' => 'Energy Monitoring',
                'icon_url' => 'https://example.com/icons/power.png',
                'url_documentation' => 'https://docs.ced-na.company.com/power',
                'sort_order' => 15,
                'is_active' => true,
                'is_strategic' => false,
                'scientific_owner' => 'Facilities Team',
                'internal_technical_contact' => 'power.admin@company.com',
                'external_technical_contact' => 'Power Monitoring Vendor',
                'external_technical_email' => 'support@power-vendor.com',
                'url_cockpit' => 'https://power.cockpit.ced-na.company.com',
                'url_sandbox' => 'https://power-test.ced-na.company.com',
                'support_contract_expiry' => now()->addMonths(12),
                'contract_notes' => 'Contratto manutenzione UPS e sistema di monitoraggio',
                'cpu' => '4 Core Intel',
                'ram' => '8 GB DDR4',
                'hd' => '256 GB SSD',
                'runtime_type' => 'vm',
                'ports' => '443, 80, 161',
                'has_mfa' => true,
                'backup_strategy' => 'Backup dati consumi e allarmi',
                'client_id' => 'power-ced-client',
                'client_secret' => 'encrypted_secret_placeholder',
            ],
            [
                'name' => 'Impianto Antincendio CED NA',
                'short_name' => 'Fire-CED',
                'description' => 'Sistema di rilevamento e spegnimento incendi del Centro Elaborazione Dati Nord America con sensori, allarmi e sistema di spegnimento automatico.',
                'url' => 'https://fire.ced-na.company.com',
                'project' => 'CED NA Safety',
                'category' => 'Fire Safety',
                'icon_url' => 'https://example.com/icons/fire.png',
                'url_documentation' => 'https://docs.ced-na.company.com/fire',
                'sort_order' => 16,
                'is_active' => true,
                'is_strategic' => true,
                'scientific_owner' => 'Safety & Security Team',
                'internal_technical_contact' => 'fire.admin@company.com',
                'external_technical_contact' => 'Fire Safety Vendor',
                'external_technical_email' => 'support@fire-safety.com',
                'url_cockpit' => 'https://fire.cockpit.ced-na.company.com',
                'url_sandbox' => 'https://fire-test.ced-na.company.com',
                'support_contract_expiry' => now()->addMonths(6),
                'contract_notes' => 'Ispezione semestrale e manutenzione sistema di spegnimento',
                'cpu' => '2 Core Intel',
                'ram' => '4 GB DDR4',
                'hd' => '128 GB SSD',
                'runtime_type' => 'appliance',
                'ports' => '443, 80, 5020',
                'has_mfa' => true,
                'backup_strategy' => 'Backup log eventi e configurazione allarmi',
                'client_id' => 'fire-ced-client',
                'client_secret' => 'encrypted_secret_placeholder',
            ],
            [
                'name' => 'VRE PISA',
                'short_name' => 'VRE-PISA',
                'description' => 'Virtual Research Environment PISA - Piattaforma di ricerca virtuale per progetti scientifici con risorse computazionali e collaborative tools.',
                'url' => 'https://vre.pisa.company.com',
                'project' => 'Research Infrastructure',
                'category' => 'Research Platform',
                'icon_url' => 'https://example.com/icons/vre.png',
                'url_documentation' => 'https://docs.vre.pisa.company.com',
                'sort_order' => 17,
                'is_active' => true,
                'is_strategic' => true,
                'scientific_owner' => 'Research Computing Team',
                'internal_technical_contact' => 'vre.admin@company.com',
                'external_technical_contact' => 'VRE Support',
                'external_technical_email' => 'support@vre.pisa.company.com',
                'url_cockpit' => 'https://vre-admin.pisa.company.com',
                'url_sandbox' => 'https://vre-test.pisa.company.com',
                'support_contract_expiry' => now()->addMonths(18),
                'contract_notes' => 'Piattaforma di ricerca con supporto tecnico dedicato',
                'cpu' => '16 Core Xeon',
                'ram' => '64 GB DDR4',
                'hd' => '2 TB SSD',
                'runtime_type' => 'container',
                'ports' => '443, 8080, 8443, 22',
                'has_mfa' => true,
                'backup_strategy' => 'Backup dati ricerca giornaliero con retention 1 anno',
                'client_id' => 'vre-pisa-client',
                'client_secret' => 'encrypted_secret_placeholder',
            ],
        ];

        $applications = [
            [
                'name' => 'OPEN SCIENCE CLOUD',
                'short_name' => 'FOSSR-Cloud',
                'description' => "Infrastruttura cloud per l'archiviazione, gestione e condivisione di dati delle scienze sociali secondo i principi FAIR. Integra nodi di calcolo distribuito e storage ad alta capacità.",
                'url' => 'https://cloud.fossr.eu',
                'category' => 'Cloud & Storage',
                'project' => 'FOSSR',
                'is_active' => true,
                'is_strategic' => true,
                'criticality_level' => 'essential',
                'hosting_type' => 'hybrid',
                'runtime_type' => 'container',
            ],
            [
                'name' => 'ITALIAN ONLINE PROBABILITY PANEL (IOPP)',
                'short_name' => 'IOPP',
                'description' => 'Panel di indagine online composto da un campione probabilistico della popolazione italiana per ricerche sociali longitudinali ad alta affidabilità statistica.',
                'url' => 'https://iopp.fossr.it',
                'category' => 'Data Collection',
                'project' => 'FOSSR',
                'is_active' => true,
                'is_strategic' => false,
                'criticality_level' => 'important',
                'hosting_type' => 'IASS',
                'runtime_type' => 'vm',
            ],
            [
                'name' => 'ONLINE RESEARCH PANEL (ORP)',
                'short_name' => 'ORP',
                'description' => 'Piattaforma digitale per la raccolta dati su larga scala tramite sondaggi online flessibili e campionamenti specializzati.',
                'url' => 'https://orp.fossr.eu',
                'category' => 'Data Collection',
                'project' => 'FOSSR',
                'is_active' => true,
                'is_strategic' => false,
                'criticality_level' => 'standard',
                'hosting_type' => 'CASS',
                'runtime_type' => 'container',
            ],
            [
                'name' => 'POLICY LEARNING PLATFORM (PLP)',
                'short_name' => 'PLP',
                'description' => "Ambiente digitale per connettere ricerca sociale e policy-making, fornendo insight basati sui dati e strumenti di simulazione dell'impatto delle politiche pubbliche.",
                'url' => 'https://plp.fossr.eu',
                'category' => 'Policy Support',
                'project' => 'FOSSR',
                'is_active' => true,
                'is_strategic' => false,
                'criticality_level' => 'important',
                'hosting_type' => 'IASS',
                'runtime_type' => 'vm',
            ],
            [
                'name' => 'SYNTHETIC POPULATIONS GENERATOR (SPG)',
                'short_name' => 'SPG',
                'description' => 'Generatore di micro-dati sintetici che rispecchiano le caratteristiche reali della popolazione senza compromettere la privacy, ideale per modelli basati su agenti.',
                'url' => 'https://spg.fossr.eu',
                'category' => 'Data Synthesis',
                'project' => 'FOSSR',
                'is_active' => true,
                'is_strategic' => false,
                'criticality_level' => 'standard',
                'hosting_type' => 'CASS',
                'runtime_type' => 'container',
            ],
            [
                'name' => 'VIRTUAL RESEARCH ENVIRONMENT (VRE)',
                'short_name' => 'VRE',
                'description' => 'Spazio di lavoro collaborativo basato sul web (JupyterHub) con strumenti di analisi integrati (R, Python) per la ricerca riproducibile.',
                'url' => 'https://vre.fossr.eu',
                'category' => 'Research Tools',
                'project' => 'FOSSR',
                'is_active' => true,
                'is_strategic' => false,
                'criticality_level' => 'essential',
                'hosting_type' => 'HPC',
                'runtime_type' => 'container',
            ],
            [
                'name' => 'GENERATIONS AND GENDER SURVEY - ROUND II (GGS-II)',
                'short_name' => 'GGS-II',
                'description' => 'Indagine longitudinale su larga scala sulle dinamiche familiari, fertilità e relazioni di genere attraverso il corso della vita.',
                'url' => 'https://ggs.fossr.eu',
                'category' => 'Survey',
                'project' => 'FOSSR',
                'is_active' => true,
                'is_strategic' => false,
                'criticality_level' => 'important',
                'hosting_type' => 'IASS',
                'runtime_type' => 'vm',
            ],
            [
                'name' => 'GROWING UP IN DIGITAL EUROPE (GUIDE)',
                'short_name' => 'GUIDE',
                'description' => 'Studio longitudinale paneuropeo focalizzato sul benessere dei bambini e dei giovani nella società digitale.',
                'url' => 'https://guide.fossr.eu',
                'category' => 'Survey',
                'project' => 'FOSSR',
                'is_active' => true,
                'is_strategic' => false,
                'criticality_level' => 'important',
                'hosting_type' => 'IASS',
                'runtime_type' => 'vm',
            ],
            [
                'name' => 'SURVEY ON HEALTH, AGEING AND RETIREMENT IN EUROPE (SHARE)',
                'short_name' => 'SHARE',
                'description' => 'Database multidisciplinare di micro-dati su salute, stato socio-economico e reti sociali di individui over 50 in Europa.',
                'url' => 'https://share.fossr.eu',
                'category' => 'Survey',
                'project' => 'FOSSR',
                'is_active' => true,
                'is_strategic' => false,
                'criticality_level' => 'essential',
                'hosting_type' => 'IASS',
                'runtime_type' => 'vm',
            ],
        ];

        foreach ($application0s as $app) {
            $app['webhook_token'] = (string) Str::uuid();
            Application::create($app);
        }

        foreach ($applications as $app) {
            $app['webhook_token'] = (string) Str::uuid();
            Application::create($app);
        }
    }
}
