<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ContactSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $contacts = [
            [
                'name' => 'Francesco Gualdaroni',
                'email' => 'f.gualdaroni@nectlc.com',
                'company' => 'NECTLC',
                'role' => null,
                'phone' => null,
                'notes' => 'Contatto principale per coordinamento progetti',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mario Ciampi',
                'email' => 'mario.ciampi@icar.cnr.it',
                'company' => 'ICAR-CNR',
                'role' => null,
                'phone' => null,
                'notes' => 'Referente ICAR-CNR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gennaro Formisano',
                'email' => 'ing.gennaroformisano@libero.it',
                'company' => null,
                'role' => 'Ing.',
                'phone' => null,
                'notes' => 'Ingegnere consulente',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Francesco De Benedictis',
                'email' => 'francesco.debenedictis@cnr.it',
                'company' => 'CNR',
                'role' => null,
                'phone' => null,
                'notes' => 'Contatto CNR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Antonio Frassanito',
                'email' => 'a.frassanito@nectlc.com',
                'company' => 'NECTLC',
                'role' => null,
                'phone' => null,
                'notes' => 'Contatto NECTLC',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Daniele Marra',
                'email' => 'd.marra@nectlc.com',
                'company' => 'NECTLC',
                'role' => null,
                'phone' => null,
                'notes' => 'Contatto NECTLC',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fabio Moncada',
                'email' => 'fabio.moncada@vertiv.com',
                'company' => 'Vertiv',
                'role' => null,
                'phone' => null,
                'notes' => 'Contatto Vertiv',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pasquale Rossi',
                'email' => 'Pasquale.Rossi@vertiv.com',
                'company' => 'Vertiv',
                'role' => null,
                'phone' => null,
                'notes' => 'Contatto Vertiv',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Alberto Di Martino',
                'email' => 'a.dimartino@firekloud.it',
                'company' => 'Firekloud',
                'role' => null,
                'phone' => null,
                'notes' => 'Contatto Firekloud',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Firetek Team',
                'email' => 'info@firetek.it',
                'company' => 'Firetek',
                'role' => null,
                'phone' => null,
                'notes' => 'Contatto generico Firetek',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'R. Bianchetti',
                'email' => 'r.bianchetti@firekloud.it',
                'company' => 'Firekloud',
                'role' => null,
                'phone' => null,
                'notes' => 'Contatto Firekloud',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SonicWall Security Team',
                'email' => 'SecurityAdvisory@msg.sonicwall.com',
                'company' => 'SonicWall',
                'role' => 'Security Advisory',
                'phone' => null,
                'notes' => 'Team sicurezza SonicWall per notifiche advisory',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Davide Vacca',
                'email' => 'davide@kaosinformatica.it',
                'company' => 'Kaos Informatica',
                'role' => null,
                'phone' => null,
                'notes' => 'Contatto Kaos Informatica',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pier Giuseppe Meo',
                'email' => 'piergiuseppe.meo@icar.cnr.it',
                'company' => 'ICAR-CNR',
                'role' => null,
                'phone' => null,
                'notes' => 'Contatto ICAR-CNR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Emanuele Damiano',
                'email' => 'emanuele.damiano@icar.cnr.it',
                'company' => 'ICAR-CNR',
                'role' => null,
                'phone' => null,
                'notes' => 'Contatto ICAR-CNR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pietro Storniolo',
                'email' => 'pietro.storniolo@icar.cnr.it',
                'company' => 'ICAR-CNR',
                'role' => null,
                'phone' => null,
                'notes' => 'Contatto ICAR-CNR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Francesco Gargiulo',
                'email' => 'francesco.gargiulo@icar.cnr.it',
                'company' => 'ICAR-CNR',
                'role' => null,
                'phone' => null,
                'notes' => 'Contatto ICAR-CNR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mario Sicuranza',
                'email' => 'mario.sicuranza@icar.cnr.it',
                'company' => 'ICAR-CNR',
                'role' => null,
                'phone' => null,
                'notes' => 'Contatto ICAR-CNR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Emilio Greco',
                'email' => 'emilio.greco@icar.cnr.it',
                'company' => 'ICAR-CNR',
                'role' => null,
                'phone' => null,
                'notes' => 'Contatto ICAR-CNR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Diego Romano',
                'email' => 'diego.romano@cnr.it',
                'company' => 'CNR',
                'role' => null,
                'phone' => null,
                'notes' => 'Contatto CNR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Alessandra Caggiano',
                'email' => 'alessandra.caggiano@linksmt.it',
                'company' => 'LinksMT',
                'role' => null,
                'phone' => null,
                'notes' => 'Contatto LinksMT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lorenza Di Lallo',
                'email' => 'lorenza.dilallo@linksmt.it',
                'company' => 'LinksMT',
                'role' => null,
                'phone' => null,
                'notes' => 'Contatto LinksMT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Alfredo Serafini',
                'email' => 'alfredo.serafini@linksmt.it',
                'company' => 'LinksMT',
                'role' => null,
                'phone' => null,
                'notes' => 'Contatto LinksMT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('contacts')->insert($contacts);
    }
}
